name: phrase_recorder
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.1.0
  cloud_firestore: ^2.0.0
  firebase_storage: ^10.0.3
  firebase_auth: ^3.1.1
  google_sign_in: ^5.1.0
  flutter_sound: ^8.1.1
  path_provider: ^2.0.1
  permission_handler: ^8.1.6
  flutter_archive: ^4.0.1
  vibration: ^1.7.4-nullsafety.0
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.0.6
  enum_to_string: ^2.0.1
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
  uses-material-design: true
